### PR TITLE
Feature: Add Windows Support

### PR DESCRIPTION
**Pull request by beyondmeat**
Fix: Windows doesn't support setting encoding
Feature: Support Environment vars for config paths
Config: Add Windows specific example

### CODE REVIEW

**Comment by desimaniac** [comment]
Old readme had some info on Windows. https://github.com/l3uddz/plex_autoscan/blob/master/README.bak.md

But none of use a Windows anymore, so doubtful we'll be able to write much about.

**Comment by beyondmeat** [comment]
@desimaniac This PR fixes 2 windows bugs, allows using environment vars (less config editing needed now) and generates a windows specific config if on Windows.

Tested and Working for me.

**Comment by beyondmeat** [comment]
I have updated the readme

**Comment by desimaniac** [comment]
Ok didn't realize this was a PR and not an Feature Request 😛. 

I'll take a look at tomorrow.

**Comment by desimaniac** [comment]
Can you split 'Feature: Support Environment vars for config paths' into its own PR?  I think it could be file done directly under config. Py module in load function. No need to rushed it in every instance of the variable call. 

If you split that up, I could merge the others and we can work on this feature separately. 

Also didn't see 'merge_two_dicts(x, y)' being used anywhere.

**Pull request closed without merging**
