### PR TITLE
Added a Dockerfile, healthcheck, start script, and documentation to the README.

### PR DESCRIPTION
**Pull request by sabrsorensen**
I've created a [Docker image](https://hub.docker.com/r/sabrsorensen/alpine-plex_autoscan) that I've been using reliably for some time now, I thought I'd offer it in a PR if you're interested.

### CODE REVIEW

**Comment by desimaniac** [comment]
Thanks will check out..

**Comment by desimaniac** [comment]
Can you give an example of what your mount points look like and the corresponding paths in the config.json ? Thanks.

**Comment by sabrsorensen** [comment]
I added some snippets from my docker-compose.yml and my config.json, do these make sense? I tried to keep it somewhat simple by having matching mountpoints in the Plex, plex_autoscan, and Sonarr/Radarr/etc containers when possible.

**Comment by desimaniac** [comment]
Thanks. The added info was helpful.

**Comment by sabrsorensen** [comment]
I just noticed that the rclone functionality in plex_autoscan changed with the introduction of crypt support, and I don't believe this image supports the new rclone configuration requirements. I'll work on adapting to these changes and follow up here when I have something ready.

**Comment by sabrsorensen** [comment]
I've been testing an image with rclone bundled in for a couple days and haven't run into an issue with it yet, so I think this is ready to go.

**Comment by desimaniac** [comment]
Same comment as the one for Cloudplow. If you create a docker image under a repo like `sabrsorensen/docker-plex-autoscan` we could just add your docker instructions in for the readme but it would be easier for you to maintain just the dockerfiles if it was your own repo.

**Pull request closed without merging**
